"""record the pull request a review came from

Revision ID: 7f852af95ccf
Revises: af10c8fa3eeb
Create Date: 2026-08-02 15:38:28.670725

Everything here is additive except the two DROP NOT NULLs. Those are forced: a
webhook has to answer 202 inside GitHub's delivery timeout, and the diff fetch is
the slow call, so the row exists before there is a diff to hash.

That makes the downgrade lossy in one direction. Restoring NOT NULL fails if any
webhook row is still pending or was written before its diff arrived, because
those rows hold NULL. Downgrading a database that has served webhooks means
deciding what to do with those rows first; it is not an automatic reverse.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f852af95ccf'
down_revision: Union[str, Sequence[str], None] = 'af10c8fa3eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('repo_full_name', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('pr_number', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('head_sha', sa.String(length=40), nullable=True))
    op.add_column('reviews', sa.Column('delivery_id', sa.String(length=64), nullable=True))
    op.add_column('reviews', sa.Column('posted_review_id', sa.BigInteger(), nullable=True))
    op.add_column('reviews', sa.Column('posted_comment_count', sa.SmallInteger(), nullable=True))
    op.add_column('reviews', sa.Column('focus', sa.Text(), nullable=True))
    op.alter_column('reviews', 'diff_sha256',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('reviews', 'diff_bytes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_reviews_repo_full_name_pr_number_head_sha', 'reviews', ['repo_full_name', 'pr_number', 'head_sha'], unique=False)
    op.create_unique_constraint(op.f('uq_reviews_delivery_id'), 'reviews', ['delivery_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_reviews_delivery_id'), 'reviews', type_='unique')
    op.drop_index('ix_reviews_repo_full_name_pr_number_head_sha', table_name='reviews')
    op.alter_column('reviews', 'diff_bytes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'diff_sha256',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('reviews', 'focus')
    op.drop_column('reviews', 'posted_comment_count')
    op.drop_column('reviews', 'posted_review_id')
    op.drop_column('reviews', 'delivery_id')
    op.drop_column('reviews', 'head_sha')
    op.drop_column('reviews', 'pr_number')
    op.drop_column('reviews', 'repo_full_name')
    # ### end Alembic commands ###
