"""initial schema

Revision ID: af10c8fa3eeb
Revises: 
Create Date: 2026-08-02 09:51:08.098366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af10c8fa3eeb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('diff_sha256', sa.String(length=64), nullable=False),
    sa.Column('diff_bytes', sa.Integer(), nullable=False),
    sa.Column('diff_path', sa.Text(), nullable=True),
    sa.Column('suppressed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('truncated_files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("source IN ('cli', 'webhook')", name=op.f('ck_reviews_source')),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed')", name=op.f('ck_reviews_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_index('ix_reviews_created_at', 'reviews', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_reviews_diff_sha256', 'reviews', ['diff_sha256'], unique=False)
    op.create_table('agent_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('findings_returned', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("agent IN ('security', 'style', 'architecture')", name=op.f('ck_agent_calls_agent')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_agent_calls_review_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_calls')),
    sa.UniqueConstraint('review_id', 'agent', name=op.f('uq_agent_calls_review_id_agent'))
    )
    op.create_index('ix_agent_calls_review_id', 'agent_calls', ['review_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.Column('file', sa.Text(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sources', sa.ARRAY(sa.Text()), nullable=False),
    sa.CheckConstraint("severity IN ('high', 'medium', 'low')", name=op.f('ck_findings_severity')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_findings_review_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings')),
    sa.UniqueConstraint('review_id', 'ordinal', name=op.f('uq_findings_review_id_ordinal'))
    )
    op.create_index('ix_findings_review_id', 'findings', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_findings_review_id', table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_agent_calls_review_id', table_name='agent_calls')
    op.drop_table('agent_calls')
    op.drop_index('ix_reviews_diff_sha256', table_name='reviews')
    op.drop_index('ix_reviews_created_at', table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
